include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    unnecessary_getters_setters: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
