name: cachecontrol
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/rodydavis/cache-control-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.24.9

